# Generated by Django 4.1.3 on 2022-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='money',
        ),
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.FloatField(default=50),
        ),
    ]
