# Generated by Django 4.1.3 on 2022-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_virtualaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='user_id',
            field=models.FloatField(default=0),
        ),
    ]
